require('lazy_bootstrap')
require('theme')
require('config.providers')
require('config.base')
require('config.maps')
require('config.windows')
require('config.autocommands')
require('config.commands')
